version: '3'

services:
  app:
    # depends_on:
    #   - db
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks: 
      - internal

  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog_db
      MYSQL_USER: myblog_user
      MYSQL_PASSWORD: myblog_password
    networks: 
        - internal

networks: 
    internal:
        driver: bridge