version: '3'

services:
  app:
    # depends_on:
    #   - db
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks: 
      - internal

  # db:
  #   image: mongo:5.0
  #   restart: unless-stopped
  #   volumes:
  #     - ./.docker/mongodb/dbdata:/data/db
  #   ports:
  #     - "27016:27017"
  #   networks: 
  #     - internal

networks: 
    internal:
        driver: bridge