version: '3'

services:
  app:
    # depends_on:
    #   - db
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks: 
      - internal

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
      - MYSQL_DATABASE=myapp_docker
    volumes: 
        - ./.docker/mysql/dbdata:/var/lib/mysql
    ports: 
        - "3388:3306"
    networks: 
        - internal

networks: 
    internal:
        driver: bridge